---
title: "Preregistration Report - Replication of the anchor effect"
output: html_notebook
---

#Study Information

Replication of the anchor effect

Inga Kramarek and Sarah Kusch

Research question: Does the first information (anchor) create a reference point to compare the further information with?

Our first hypothesis is directional and we assume that those participants who receive a low anchor give a significantly lower absolute estimate than those who receive a high anchor irrespective of the question's content.

Our second hypothesis is non-directional and states that there is no significant difference in estimates between participants who know the anchor effect and those who do not.

# Sampling Plan

  1. Existing data
     
    This registration is prior to the creation of the data. We will collect and analyze data only after the submission of our research plan.
  
  2. Data collection procedures
    
    There are no constraints to obtain human-subjects since there are not any constrains for the anchor effect to appear. This experiment is a study project, so we do not have any money available to conduct the experiment. Therefore we will mainly recruit other students via the university network and everyone we can recruit via social networks.
    
  3. Sample size
  
    We will try to recruit as many people as possible for our experiment, but at least 30 subjects.
    
  4. Sample size ratio
  
    Time is the only constraint of the recruitment.
    
  5. Stopping rule
  
    We will stop the data collection when we reach our recruiting deadline of two weeks to get as many subjects as possible.
    

# Variables

  1. Manipulated variables
  
    The manipulated variable, hereinafter referred to as "anchor variable", can take the values 'high' or 'low' and indicates whether the question contained a low or a high anchor. Each participant will receive six questions with a low and six with a high anchor. 
    
  2. Measured variables
  
    We will measure the absolute estimation the participants give for each of the 12 questions. As well as whether the participants know about the anchor effect or not, hereafter "knowledge variable".

  3. Indices
  
    We will z-transform all estimates per question to eliminate the different units. Then we will avarage across all z-transformed estimates per anchor condition and per participant to determine the participant's mean estimate in the low and high anchor condition respectively. This will yield two mean z-scores per participant per condition.
    
  
# Design Plan

  The experiment will be conducted without any blinding since it is an online questionnaire that the participants will fill out at home. It is a within-subject, cross-sectional design and uses repeated measures.
  The questionnaire consists of 2 practice trials and 12 main trials. In each trial the subject first has to choose between two answer options to an estimation question. Secondly, the subject has to give an exact estimate to the same question.
  The assignment of high and low anchors to the questions is randomized, but each questionnaire has the same amount of question with a high anchor and low anchor.
  
  Example:
  
  1. Is the length of the river 'Rhein' higher or lower than 200km (low anchor)/1200km (high anchor)?
  2. Estimate the exact length of the river 'Rhein'
  

# Analysis Plan

For the first hypothesis we will use a paired t-test with the outcome (dependent variable) being the z-transformed estimates per participant and per anchor condition. The predictor (independent variable) is the anchor variable.

The second hypothesis will be tested using a linear mixed model with random intercept per participant and per question. The predictors are the anchor variable and additionally the kowledge variable. The outcome (dependent variable) will be the z-transformed estimates per participant and per anchor condition. We are going to analyse the main effect of the knowledge variable.

We will z-transform the given estimates as described under "Variables" "3. Indices". We will not do any follow-up analyses.

For our analysis we will use  $\alpha = 0.05$ as an inference criterion. Both hypothesis will be tested one-tailed and the direction of the first hypothesis will be checked by comparing the mean estimates of the high and low anchor condition. 

We will exclude outliers, i.e. in this case, impossible answers, since our main statistical measurement is the mean and it is sensitive to outliers. We do not have predefined cut-off values per question but we will decide on a case by case basis and report this in the final paper.
The experiment is implemented in such a way that the participant has to give an answer in order to proceed to the next question. Thus we do not expect missing data except the participant aborts the experiment. In this case we will not include the participant's data.
