---
title: "Summary Analysis"
output: html_notebook
---


#### Main Hypothesis:

Those who receive a low anchor make a significantly lower absolute estimate compared to those who receive a high anchor.

$$H_0: \mu_1 \ge \mu_2 \\H_1: \mu_1 \lt \mu_2 $$
With $\mu_1$ being the the population mean of the estimates following a low anchor and $\mu_2$ being the population mean of the estimates following a high anchor. The dependent variable is the absolute estimate given (per person per anchor condition). The independent variable tells whether a low or high anchor was given. We will test this hypothesis by performing a t-test for repeated measures. In order to avarage across all questions to determine the participant's mean estimate for the low and high anchor condition respectively, we first have to z-transform all estimates per person across each question. This will yield two mean z-scores per person per anchor condition. To check whether the requirements of the paired t-test are fullfiled, we use the Lilliefors test to check for normality of the difference between the two mean z-scores of each participant. If the difference is normally distributed we will do the t-test for repeated samples since the groups (low vs. high anchor condition) are dependent. If the p-value of the t-test is below 0.05 we will reject the null hypothesis.

Before the actual testing we need to clean our data. We will check for outliers in reaction time and for impossible answers. In order to rule out that questions have been looked up during testing and those answer which are arguably not possible.

## Additional Hypothesis

With our second, exploratory hyothesis we want to test whether knowledge about the anchor effect influences the strength of the anchor effect. It might be that if someone knows about the influence of an anchor that she is less influenced by it. Thus we want to test whether the difference between the mean z-scores under the low anchor condition and the high anchor condition differ between the two independent groups which either have knowledge of the anchor effect or do not. We will test this by using a mixed model ##### TODO #####  .Since we do not control for knowledge about the anchor effect, by now we cannot say whether we will be able to test this hypothesis. For testing we need about the same amount of participants in both groups. ###TODO#### Voraussetzungen?!

